name: Build package

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - LICENSE
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - LICENSE

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    strategy:
      matrix:
        session:
          - black
          - mypy
          - ruff
      fail-fast: false
    steps:
      - name: Check out 🎉
        uses: actions/checkout@v4.2.2
      - name: Set up uv 🐍
        uses: astral-sh/setup-uv@v9.0.0
        with:
          enable-cache: true
      - name: Install Nox 📦
        run: |
          uv sync --only-group=nox --locked
      - name: Run Nox 🦊
        run:
          uv run nox -s ${{ matrix.session }}
  test:
    name: Run tests
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
      fail-fast: false
    steps:
      - name: Check out 🎉
        uses: actions/checkout@v4.2.2
      - name: Set up uv 🐍
        uses: astral-sh/setup-uv@v9.0.0
        with:
          enable-cache: true
      - name: Install Nox 📦
        run: |
          uv sync --only-group=nox --locked
      - name: Run Nox 🦊
        run:
          nox -s test
      - name: Upload coverage reports to Codecov ⛱️
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v5.1.2
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
