name: Build package

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - LICENSE
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - LICENSE

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    strategy:
      matrix:
        session:
          - black
          - mypy
          - ruff
      fail-fast: false
    steps:
      - name: Check out 🎉
        uses: actions/checkout@v7.0.1
      - name: Set up uv 🐍
        uses: astral-sh/setup-uv@v9.0.0
        with:
          enable-cache: true
      - name: Install Nox 📦
        run: |
          uv sync --only-group=nox --locked
      - name: Run Nox 🦊
        run:
          uv run --no-sync nox -s ${{ matrix.session }}
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out 🎉
        uses: actions/checkout@v7.0.1
      - name: Set up uv 🐍
        uses: astral-sh/setup-uv@v9.0.0
        with:
          enable-cache: true
      - name: Install Nox 📦
        run: |
          uv sync --only-group=nox --locked
      - name: Run Nox 🦊
        run:
          uv run --no-sync nox -s test -- --cov --cov-append --cov-report=xml:coverage.xml
      - name: Upload coverage reports to Codecov ⛱️
        uses: codecov/codecov-action@v7.0.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
