name: Sync the backup with the API

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  sync:
    name: Sync and create PR
    runs-on: ubuntu-latest
    steps:
      - name: Check out 🎉
        uses: actions/checkout@v4.4.0
      - name: Set up uv 🐍
        uses: astral-sh/setup-uv@v9.0.0
        with:
          enable-cache: true
      - name: Install the package 📦
        run: |
          uv sync --no-dev --locked
      - name: Run the `sync` command 🚀
        run:
          uv run gitmojis sync
      - name: Create pull request 🎉
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          token: ${{ secrets.CREATE_PR_ACTION_TOKEN }}
          commit-message: 🍱 Update the backup file with the Gitmoji API data
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          branch: sync-backup-file-with-api
          branch-suffix: short-commit-hash
          title: 🍱 Update the backup file with the Gitmoji API data
          body: |
            ## Description

            The backup file has been updated to represent the current state of the official Gitmoji API. 🎉

            ℹ️ Automated changes by [Create Pull Request](https://github.com/peter-evans/create-pull-request) action by Peter Evans.
          assignees: paduszyk
          labels: chores
